routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('home');
Route::get('antrian', 'PageController@antrian')->name('antrian');
Route::post('antri/{id}', 'PageController@antri')->name('antri');
Route::post('proses/{id}', 'PageController@proses')->name('proses');
Route::post('memilih/{calon}/{mhs}', 'PageController@memilih')->name('memilih');
Route::post('golput', 'PageController@golput')->name('golput');
Route::get('count', 'PageController@count')->name('count');

/**
 * Login
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
	Route::get('/', 'PageController@dashboard')->name('dashboard');
	Route::get('quick-count', 'PageController@quick')->name('quick');
	Route::get('logs', 'LogController@index')->name('log');
	Route::resource('calons', 'CalonController');
	Route::resource('mhs', 'MhsController');
	Route::resource('users', 'UsersController');
	Route::resource('roles', 'RolesController');
	Route::resource('settings', 'SettingController', ['only' => ['index', 'edit', 'update']]);
});

Route::get('dump', function () {
	$no = 1;
	foreach (App\Mahasiswa::select('id', 'nim', 'name', 'fakultas')->whereNull('kode')->get()->toArray() as $r) {
		$r['no'] = $no++;
		$r['action'] = "<form method='POST' action='http://pemilu.dev/antri/". $r['id'] ."' accept-charset='UTF-8'><input name='_token' type='hidden' value='". csrf_token() ."'> <input class='btn btn-xs btn-info' type='submit' value='Antri'> </form> ";
		$mhs[] = (object) $r;
	}
	$data = collect($mhs);
	if (request()->ajax()) {
		// return Datatables::of($data)->make(true);
		return response()->json(compact('data'));
	}
	$f = Faker\Factory::create('id_ID');
	foreach (range(1, 7500) as $r) {
		$data = collect([(object)['nim' => 'B', 'fakultas' => 'EKONOMI'], (object)['nim' => 'C', 'fakultas' => 'TEKNIK'], (object)['nim' => 'D', 'fakultas' => 'PERTANIAN'], (object)['nim' => 'E', 'fakultas' => 'HUKUM'], (object)['nim' => 'F', 'fakultas' => 'PSIKOLOG'], (object)['nim' => 'G', 'fakultas' => 'TIK']]);
		$kd = collect(['211', '131', '111', '311', '121']);
		$fk = $data->random();
		$nim = $fk->nim . '.' . $kd->random() . '.' . rand(13,16) . '.' . substr('0000'. rand(1,100), -4);
		$name = $f->firstName . ' ' . $f->lastName;
		do {
			$nimf = $nim;
			if (count(App\Mahasiswa::whereNim($nim)->first()) >= 1) {
				$fk = $data->random();
				$nim = $fk->nim . '.' . $kd->random() . '.' . rand(13,16) . '.' . substr('0000'. rand(1,200), -4);
				dump("Ganti $nimf ke $nim");
			}
		} while (count(App\Mahasiswa::whereNim($nim)->first()) >= 1);
		dump($nim, $name);
		App\Mahasiswa::create(['name' => $name, 'nim' => $nim, 'fakultas' => $fk->fakultas]);
	}
})->name('datatables.data');
Route::get('data', function () {
	return view('datatable');
});

resources/views/partials/head.blade.php
<meta charset="utf-8">
<title>
    Admin
</title>

@yield('meta')
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="{{ url('assets/css') }}/font-awesome.min.css"/>
<link rel="stylesheet" href="{{ url('assets/css') }}/bootstrap.min.css"/>
<link rel="stylesheet" href="{{ url('assets/css') }}/components.css"/>
<link rel="stylesheet" href="{{ url('assets/css') }}/quickadmin-layout.css"/>
<link rel="stylesheet" href="{{ url('assets/css') }}/quickadmin-theme-default.css"/>
<link rel="stylesheet" href="{{ url('assets/css') }}/select2.min.css"/>
<link rel="stylesheet" href="{{ url('assets/css') }}/jquery-ui.min.css">
<link rel="stylesheet" href="{{ url('datatables') }}/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" href="{{ url('datatables/extension') }}/css/select.dataTables.min.css"/>
<link rel="stylesheet" href="{{ url('datatables/extension') }}/css/buttons.dataTables.min.css"/>
<link rel="stylesheet" href="{{ url('timepicker') }}/jquery-ui-timepicker-addon.min.css"/>
<link rel="stylesheet" href="{{ url('datepicker') }}/css/bootstrap-datepicker3.standalone.min.css"/>

@yield('style')

resources/views/partials/header.blade.php
<div class="page-header-inner">
    <div class="page-header-inner">
        <div class="navbar-header">
            <a href="{{ route('dashboard') }}"
               class="navbar-brand">
                Admin
            </a>
        </div>
        <a href="javascript:;"
           class="menu-toggler responsive-toggler"
           data-toggle="collapse"
           data-target=".navbar-collapse">
        </a>

        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
              <li class="hidden-xs"><button type="button" class="btn btn-link" style="margin-top: 5px; text-decoration: none; color: #fff;"><strong>{{ strtoupper(auth()->user()->roles()->first()->title) }}</strong> | <i class="fa fa-user"></i> {{ ucwords(auth()->user()->name) }}</button></li>
            </ul>
        </div>
    </div>
</div>

resources/views/partials/javascripts.blade.php
<script src="{{ url('assets/js') }}/jquery.js"></script>
<script src="{{ url('datatables') }}/js/jquery.dataTables.min.js"></script>
<script src="{{ url('datatables/extension') }}/js/dataTables.buttons.min.js"></script>
<script src="{{ url('datatables/extension') }}/js/buttons.flash.min.js"></script>
<script src="{{ url('jszip') }}/jszip.min.js"></script>
<script src="{{ url('pdfmake') }}/pdfmake.min.js"></script>
<script src="{{ url('pdfmake') }}/vfs_fonts.js"></script>
<script src="{{ url('datatables/extension') }}/js/buttons.html5.min.js"></script>
<script src="{{ url('datatables/extension') }}/js/buttons.print.min.js"></script>
<script src="{{ url('datatables/extension') }}/js/buttons.colVis.min.js"></script>
<script src="{{ url('datatables/extension') }}/js/dataTables.select.min.js"></script>
<script src="{{ url('assets/js') }}/jquery-ui.min.js"></script>
<script src="{{ url('assets/js') }}/bootstrap.min.js"></script>
<script src="{{ url('assets/js') }}/select2.full.min.js"></script>
<script src="{{ url('assets/js') }}/main.js"></script>

<script>
    window._token = '{{ csrf_token() }}';
</script>

@yield('javascript')

resources/views/partials/sidebar.blade.php
@inject('request', 'Illuminate\Http\Request')
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu"
            data-keep-expanded="false"
            data-auto-scroll="true"
            data-slide-speed="200">
            <li class="{{ is_null($request->segment(2)) ? 'active' : '' }}">
                <a href="{{ route('dashboard') }}">
                    <i class="fa fa-dashboard"></i>
                    <span class="title">@lang('quickadmin.dashboard')</span>
                </a>
            </li>
            @if(strtolower(auth()->user()->roles()->first()->title) == 'administrator')
            <li class="{{ $request->segment(2) == 'quick-count' ? 'active' : '' }}">
                <a href="{{ route('quick') }}">
                    <i class="fa fa-history"></i>
                    <span class="title">Quick Count</span>
                </a>
            </li>
            @endif
            @if(strtolower(auth()->user()->roles()->first()->title) == 'pengawas' || strtolower(auth()->user()->roles()->first()->title) == 'administrator')
            <li class="{{ $request->segment(2) == 'calons' ? 'active' : '' }}">
                <a href="{{ route('calons.index') }}">
                    <i class="fa fa-user"></i>
                    <span class="title">Calons</span>
                </a>
            </li>
            @endif
            @if(strtolower(auth()->user()->roles()->first()->title) == 'pengawas' || strtolower(auth()->user()->roles()->first()->title) == 'administrator')
            <li class="{{ $request->segment(2) == 'mhs' ? 'active' : '' }}">
                <a href="{{ route('mhs.index') }}">
                    <i class="fa fa-list-alt"></i>
                    <span class="title">Mahasiswa</span>
                </a>
            </li>
            <li class="{{ $request->segment(2) == 'settings' ? 'active' : '' }}">
                <a href="{{ route('settings.index') }}">
                    <i class="fa fa-gears"></i>
                    <span class="title">Settings</span>
                </a>
            </li>
            <li class="{{ $request->segment(2) == 'logs' ? 'active' : '' }}">
                <a href="{{ route('log') }}">
                    <i class="fa fa-exchange"></i>
                    <span class="title">Log</span>
                </a>
            </li>
            @endif
            @if(strtolower(auth()->user()->roles()->first()->title) == 'administrator')
            <li class="">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span class="title">@lang('quickadmin.user-management.title')</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="sub-menu">
                
                <li class="{{ $request->segment(2) == 'roles' ? 'active active-sub' : '' }}">
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-briefcase"></i>
                            <span class="title">
                                @lang('quickadmin.roles.title')
                            </span>
                        </a>
                    </li>
                <li class="{{ $request->segment(2) == 'users' ? 'active active-sub' : '' }}">
                        <a href="{{ route('users.index') }}">
                            <i class="fa fa-user"></i>
                            <span class="title">
                                @lang('quickadmin.users.title')
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
            @endif
            <li>
                <a href="#logout" onclick="$('#logout').submit();">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">@lang('quickadmin.logout')</span>
                </a>
            </li>
        </ul>
    </div>
</div>
{!! Form::open(['route' => 'logout', 'style' => 'display:none;', 'id' => 'logout']) !!}
<button type="submit">@lang('quickadmin.logout')</button>
{!! Form::close() !!}

resources/views/partials/topbar.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner">
        <div class="page-header-inner">
            <div class="navbar-header">
                <a href="{{ url('/home') }}"
                   class="navbar-brand">
                    @lang('quickadmin.quickadmin_title')
                </a>
            </div>
            
            <a href="javascript:;"
               class="menu-toggler responsive-toggler"
               data-toggle="collapse"
               data-target=".navbar-collapse">
            </a>

            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">

                </ul>
            </div>
        </div>
    </div>
</div>